/*
ncloud

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Decrypt200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Decrypt200Response{}

// Decrypt200Response struct for Decrypt200Response
type Decrypt200Response struct {
	Code *string `json:"code,omitempty"`
	Msg *string `json:"msg,omitempty"`
	Data *Decrypt200ResponseData `json:"data,omitempty"`
}

// NewDecrypt200Response instantiates a new Decrypt200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDecrypt200Response() *Decrypt200Response {
	this := Decrypt200Response{}
	return &this
}

// NewDecrypt200ResponseWithDefaults instantiates a new Decrypt200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDecrypt200ResponseWithDefaults() *Decrypt200Response {
	this := Decrypt200Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *Decrypt200Response) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Decrypt200Response) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *Decrypt200Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *Decrypt200Response) SetCode(v string) {
	o.Code = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *Decrypt200Response) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Decrypt200Response) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *Decrypt200Response) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *Decrypt200Response) SetMsg(v string) {
	o.Msg = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *Decrypt200Response) GetData() Decrypt200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret Decrypt200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Decrypt200Response) GetDataOk() (*Decrypt200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *Decrypt200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given Decrypt200ResponseData and assigns it to the Data field.
func (o *Decrypt200Response) SetData(v Decrypt200ResponseData) {
	o.Data = &v
}

func (o Decrypt200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Decrypt200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableDecrypt200Response struct {
	value *Decrypt200Response
	isSet bool
}

func (v NullableDecrypt200Response) Get() *Decrypt200Response {
	return v.value
}

func (v *NullableDecrypt200Response) Set(val *Decrypt200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDecrypt200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDecrypt200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDecrypt200Response(val *Decrypt200Response) *NullableDecrypt200Response {
	return &NullableDecrypt200Response{value: val, isSet: true}
}

func (v NullableDecrypt200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDecrypt200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


