/*
ncloud

Testing KmsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_KmsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test KmsAPIService Decrypt", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyTag string

		resp, httpRes, err := apiClient.KmsAPI.Decrypt(context.Background(), keyTag).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KmsAPIService Encrypt", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyTag string

		resp, httpRes, err := apiClient.KmsAPI.Encrypt(context.Background(), keyTag).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
